Repository soyoung125/fin-the-pen-web, pull requests merged in 2023-10, with the labels that each got.

#64 chore: .env로 msw 모드를 끌 수 있도록 처리한다.
  src/main.tsx
Labels: 설정

#72 refactor: recoil과 관련된 모든 코드를 제거하고 redux toolkit으로 복구한다
  README.md
  package-lock.json
  package.json
  src/app/recoil/bottomDrawer.ts
  src/app/recoil/bottomTabMenu.ts
  src/app/recoil/header.ts
  src/app/recoil/isAuthenticated.ts
  src/app/redux/slices/commonSlice.tsx
  src/app/utils/storageEffect.ts
  src/components/layouts/containerLayout/AnalysisLayout.tsx
  src/components/layouts/containerLayout/ManagementLayout.tsx
  src/configs/recoil.ts
  src/containers/analysis/AnalysisContainer/index.tsx
  src/containers/assetManagement/RegularDepositWithDrawalContainer/index.tsx
  src/containers/assetManagement/SavingsGoalContainer/index.tsx
  src/containers/home/AssetView.tsx
  src/containers/home/HomeContainer/view/FetchPaymentHistory/InputForm.tsx
  src/containers/home/HomeContainer/view/FetchPaymentHistory/OptionSelector.tsx
  src/containers/home/HomeContainer/view/FetchPaymentHistory/index.tsx
  src/containers/home/HomeContainer/view/ScheduleList/ScheduleCard.tsx
  src/containers/home/HomeContainer/view/SearchSchedule/index.tsx
  src/containers/home/ScheduleDrawer/layouts/ScheduleDrawerFooter.tsx
  src/containers/home/common/BottomBar.tsx
  src/containers/home/common/TopBar/buttons/BackButton.tsx
  src/containers/home/common/TopBar/buttons/PersonalButton.tsx
  src/containers/home/common/TopBar/buttons/SearchButton/index.tsx
  src/containers/home/common/TopBar/buttons/SearchButton/popover/OptionList.tsx
  src/containers/home/common/TopBar/headerMode/SettingsMode.tsx
  src/containers/home/common/TopBar/index.tsx
  src/containers/settings/SettingsContainer.tsx
  src/containers/settings/connection/MyData/index.tsx
  src/containers/sign/EasyAuthentication.tsx
  src/hooks/useHeader.tsx
  src/main.tsx
  src/pages/AssetManagement/AssetManagement.tsx
  src/pages/Home/Home.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/UserData.tsx
  src/pages/SignIn/SignIn.tsx
  src/pages/SignUp/SignUp.tsx
  src/types/common.tsx
  yarn.lock
Labels: 설정, 리팩터링

#77 feat: 뒤로가기 버튼 동작 오류 수정
  src/components/common/RoundedButton.tsx
  src/components/fetchPaymentHistory/OrderByInput/index.tsx
  src/containers/home/HomeContainer/view/FetchPaymentHistory/InputForm.tsx
  src/containers/home/HomeContainer/view/FetchPaymentHistory/index.tsx
  src/containers/home/common/TopBar/buttons/BackButton.tsx
  src/containers/settings/SettingsContainer.tsx
  src/containers/settings/connection/MyData/index.tsx
Labels: 버그

#79 refactor: 게스트 모드를 임시 복구한다
  src/app/tanstack-query/useAuth.ts
  src/pages/MyPage/UserData.tsx
  src/pages/SignIn/MockSignIn.tsx
Labels: 리팩터링
